### ISSUE TITLE
WinError 267

### ISSUE THREAD

**Issue by ps9292** [acolite/acolite_ls2#7]
Good Day, Sir.
May I ask you something?

I got an error message during the execution. How can I solve the matter?
For your reference, my python version is 3.8 in anaconda. and OS is Win10.

Selected E:/Satellite/Sentinel_2/test/S2A_MSIL1C_20200815T021611_N0209_R003_T52SBD_20200815T043159_1 as input file.
Running ACOLITE processing
Logging to file E:/Satellite/Sentinel_2/test/S2A_MSIL1C_20200815T021611_N0209_R003_T52SBD_20200815T043159_2/acolite_run_20201020_210123_log.txt
Running ACOLITE processing on Mac/Windows.
Launching ACOLITE Python!
Started ACOLITE Python processing
Wrote run settings file to E:/Satellite/Sentinel_2/test/S2A_MSIL1C_20200815T021611_N0209_R003_T52SBD_20200815T043159_2/acolite_run_20201020_210123_settings.txt
Processing 1 scene...
Processing scene 1 of 1...
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\LaSOMS_PC_Hokun\Anaconda3\envs\acolite-master\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "E:\Satellite\Tools\acolite-master\acolite\acolite\acolite_gui.py", line 467, in startRun
    acolite_run(settings=self.acolite_settings, gui=True)
  File "E:\Satellite\Tools\acolite-master\acolite\acolite\acolite_run.py", line 180, in acolite_run
    ret = acolite.acolite_ac(scene, setu['output'], limit=setu['limit'],
  File "E:\Satellite\Tools\acolite-master\acolite\acolite\acolite_ac.py", line 232, in acolite_ac
    safe_files = pp.sentinel.safe_test(bundle)
  File "E:\Satellite\Tools\acolite-master\acolite\sentinel\safe_test.py", line 37, in safe_test
    granule_files = os.listdir(path)
NotADirectoryError: [WinError 267] The Directory Name Is Invalid 'E:/Satellite/Sentinel_2/test/S2A_MSIL1C_20200815T021611_N0209_R003_T52SBD_20200815T043159_1/GRANULE/L1C_T52SBD_A026884_20200815T021609_$folder$/'

**Comment by acolite** [comment]
Thanks for your report. This scene (S2A_MSIL1C_20200815T021611_N0209_R003_T52SBD_20200815T043159.SAFE) processes fine for me. Did you modify the file structure of the L1C file?  Could you list the file tree in the scene you are processing?
